---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by enzol.
--- DateTime: 21/10/2022 18:33
---

fx_version 'cerulean'
game 'gta5'

client_script {
'client/*.lua',
'build/client/client.js'
}

ui_page "build/index.html"

files {
    "build/index.html",
    "build/main.js"
}